export const ITEM_CREATE_REQUEST = "ITEM_CREATE_REQUEST";
export const ITEM_CREATE_SUCCESS = "ITEM_CREATE_SUCCESS"
export const ITEM_CREATE_FAIL = "ITEM_CREATE_FAIL"

export const ITEM_EDIT_REQUEST = "ITEM_EDIT_REQUEST";
export const ITEM_EDIT_SUCCESS = "ITEM_EDIT_SUCCESS"
export const ITEM_EDIT_FAIL = "ITEM_EDIT_FAIL"

export const ITEM_DELETE_REQUEST = "ITEM_DELETE_REQUEST";
export const ITEM_DELETE_SUCCESS = "ITEM_DELETE_SUCCESS"
export const ITEM_DELETE_FAIL = "ITEM_DELETE_FAIL"

export const ITEM_SORT_REQUEST = "ITEM_SORT_REQUEST";
export const ITEM_SORT_SUCCESS = "ITEM_SORT_SUCCESS"
export const ITEM_SORT_FAIL = "ITEM_SORT_FAIL"